version: '3.9'

services:
  consumerterminal:
    image: ${DOCKER_REGISTRY-}consumerterminal
    build:
      context: .
      dockerfile: ConsumerTerminal/Dockerfile

  kafkawebapi:
    image: ${DOCKER_REGISTRY-}kafkawebapi
    build:
      context: .
      dockerfile: KafkaWebAPI/Dockerfile
    ports:
      - "9093:80"
      - "9094:443"


  ttmh-eda-his:
    image: ${DOCKER_REGISTRY-}ttmhedahis
    build:
      context: .
      dockerfile: TTMH-EDA-HIS/Dockerfile
    ports:
      - "9095:80"
      - "9096:443"
    volumes: 
      - "C:/Users/NickLu/AppData/Roaming/Microsoft/UserSecrets/37fb17ff-be5f-4a15-b4bb-cde312f1e4b1/secrets.json:/root/.aspnet/DataProtection-Keys"

